---

- name: Convert network configuration to new DNS
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DNS1*'
    line: 'DNS1="{{ DNSSERVER }}"'

- name: Copy new resolv
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

